name: halc
channels:
  - pytorch
  - defaults
  - anaconda
  - main
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit-dev=11.7
  - pip
  - spacy
  - spacy-model-en_core_web_sm=3.5.0
  - pip:
    - torch==2.0.0
    - torchaudio
    - torchvision
    - huggingface-hub==0.20.2
    - matplotlib==3.7.0
    - psutil==5.9.4
    - iopath
    - pyyaml==6.0
    - regex==2022.10.31
    - tokenizers==0.15.0
    - tqdm==4.64.1
    - -e ./transformers-4.36.2
    - timm==0.6.13
    - webdataset==0.2.48
    - omegaconf==2.3.0
    - opencv-python==4.7.0.72
    - decord==0.6.0
    - peft==0.2.0
    - sentence-transformers
    - gradio==3.47.1
    - accelerate==0.26.1
    - bitsandbytes==0.37.0
    - scikit-image
    - visual-genome
    - wandb
    - seaborn
    - pandas
    - shortuuid
    - chardet
    - openai
    - supervision
    - addict
    - yapf
    - pycocotools
    - pycocoevalcap
    - icecream
